version: "3.9"

services:
  mysql-hmdp:
    image: mysql:8
    container_name: mysql-hmdp
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hmdp
      MYSQL_USER: hmdp
      MYSQL_PASSWORD: hmdp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7
    container_name: redis-hmdp
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
