services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-hmdp
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./configs/observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-hmdp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
    volumes:
      - ./configs/observability/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./configs/observability/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./configs/observability/grafana/hmdp-backend-dashboard.json:/etc/grafana/provisioning/dashboards/hmdp-backend-dashboard.json:ro
    depends_on:
      - prometheus
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-hmdp
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "4317:4317"
